
CREATE TABLE IF NOT EXISTS `#__chpanel_bookings` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `hotel_id` bigint(20) unsigned NOT NULL,
  `room_id` bigint(20) NOT NULL,
  `session_id` char(100) NOT NULL,
  `ip` varchar(1024) NOT NULL,
  `voucher` char(6) NOT NULL,
  `first_name` varchar(255) NOT NULL,
  `last_name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(255) NOT NULL,
  `street` varchar(255) NOT NULL,
  `city` varchar(255) NOT NULL,
  `zip` varchar(255) NOT NULL,
  `country` char(2) NOT NULL,
  `comments` varchar(2048) NOT NULL,
  `notes` text NOT NULL,
  `language` char(7) NOT NULL,
  `checkin` date NOT NULL,
  `checkout` date NOT NULL,
  `board` char(2) NOT NULL,
  `adult` smallint(4) NOT NULL,
  `child` smallint(4) NOT NULL,
  `baby` smallint(4) NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `payment` decimal(10,2) NOT NULL,
  `status` smallint(6) NOT NULL,
  `payment_status` tinyint(1) NOT NULL,
  `payment_ref` varchar(1024) NOT NULL,
  `payment_auth` varchar(1024) NOT NULL,
  `params` mediumtext NOT NULL,
  `state` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL,
  `created_by` int(11) NOT NULL,
  `modified` datetime NOT NULL,
  `modified_by` int(11) NOT NULL,
  `checked_out_time` datetime NOT NULL,
  `checked_out` int(11) NOT NULL,
  UNIQUE KEY `idx_id` (`id`),
  KEY `idx_state` (`state`),
  KEY `idx_checkout` (`checked_out`),
  KEY `idx_createdby` (`created_by`),
  KEY `idx_hotelid` (`hotel_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10000;

CREATE TABLE IF NOT EXISTS `#__chpanel_hotels` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `language` char(7) NOT NULL,
  `title` varchar(255) NOT NULL,
  `alias` varchar(255) NOT NULL,
  `info` text NOT NULL,
  `text` text NOT NULL,
  `conditions` text NOT NULL,
  `video` varchar(255) NOT NULL,
  `street` varchar(1024) NOT NULL,
  `zip` varchar(255) NOT NULL,
  `city` varchar(255) NOT NULL,
  `region` varchar(255) NOT NULL,
  `country` varchar(255) NOT NULL,
  `phone` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `lat` float(10,6) NOT NULL,
  `lng` float(10,6) NOT NULL,
  `zoom` tinyint(2) NOT NULL,
  `timezone` varchar(1024) NOT NULL,
  `notify` varchar(2048) NOT NULL,
  `params` text NOT NULL,
  `state` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL,
  `created_by` int(11) NOT NULL,
  `modified` datetime NOT NULL,
  `modified_by` int(11) NOT NULL,
  `checked_out_time` datetime NOT NULL,
  `checked_out` int(11) NOT NULL,
  UNIQUE KEY `idx_id` (`id`),
  KEY `idx_state` (`state`),
  KEY `idx_checkout` (`checked_out`),
  KEY `idx_createdby` (`created_by`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10000;

CREATE TABLE IF NOT EXISTS `#__chpanel_images` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `hotel_id` bigint(20) unsigned NOT NULL,
  `title` varchar(255) NOT NULL,
  `info` text NOT NULL,
  `params` text NOT NULL,
  `ordering` int(11) NOT NULL DEFAULT '0',
  `state` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL,
  `created_by` int(11) NOT NULL,
  `modified` datetime NOT NULL,
  `modified_by` int(11) NOT NULL,
  `checked_out_time` datetime NOT NULL,
  `checked_out` int(11) NOT NULL,
  UNIQUE KEY `idx_id` (`id`),
  KEY `idx_state` (`state`),
  KEY `idx_checkout` (`checked_out`),
  KEY `idx_createdby` (`created_by`),
  KEY `idx_hotelid` (`hotel_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10000;

CREATE TABLE IF NOT EXISTS `#__chpanel_inventory` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `room_id` int(11) NOT NULL,
  `date` date NOT NULL,
  `rate` decimal(10,2) NOT NULL,
  `availability` smallint(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `room_id` (`room_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__chpanel_rooms` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `hotel_id` bigint(20) unsigned NOT NULL,
  `title` varchar(255) NOT NULL,
  `alias` varchar(255) NOT NULL,
  `reference` varchar(100) NOT NULL,
  `info` text NOT NULL,
  `text` text NOT NULL,
  `video` varchar(255) NOT NULL,
  `capacity` tinyint(2) NOT NULL,
  `max_adult` tinyint(2) NOT NULL,
  `max_child` tinyint(2) NOT NULL,
  `max_baby` tinyint(2) NOT NULL,
  `rate` decimal(10,2) NOT NULL,
  `release` smallint(6) NOT NULL,
  `minstay` smallint(6) NOT NULL,
  `params` text NOT NULL,
  `ordering` int(11) NOT NULL DEFAULT '0',
  `state` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL,
  `created_by` int(11) NOT NULL,
  `modified` datetime NOT NULL,
  `modified_by` int(11) NOT NULL,
  `checked_out_time` datetime NOT NULL,
  `checked_out` int(11) NOT NULL,
  UNIQUE KEY `idx_id` (`id`),
  KEY `idx_state` (`state`),
  KEY `idx_checkout` (`checked_out`),
  KEY `idx_createdby` (`created_by`),
  KEY `idx_hotelid` (`hotel_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10000;

CREATE TABLE IF NOT EXISTS `#__chpanel_translations` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `hotel_id` bigint(20) unsigned NOT NULL,
  `lang` char(7) NOT NULL,
  `alias` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL,
  `translation` text NOT NULL,
  `created` datetime NOT NULL,
  `created_by` int(11) NOT NULL,
  UNIQUE KEY `idx_id` (`id`),
  KEY `idx_refid` (`hotel_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10000;